import React from 'react';
import PolicyPage, { Section } from './PolicyPage.jsx';

export default function Privacy() {
  return (
    <PolicyPage title="Privacy Policy" updated="September 1, 2026">
      <Section h="1. Who we are">
        <p>
          Waguan is an end-to-end encrypted messaging service that lets you send text messages, share photos and voice notes,
          and make voice and video calls. This policy explains what personal data we collect, why, and what you can do about it.
          Contact us at <span className="text-accentDark dark:text-accent">privacy@example.com</span> for any question about your data.
        </p>
      </Section>

      <Section h="2. Information you provide">
        <ul className="list-disc pl-5 space-y-1">
          <li>Account details: your name, phone number, optional username, "about" text and profile picture.</li>
          <li>Chats you create, group names, and who you add to them.</li>
          <li>Media you upload (photos, voice notes, videos) — see section 3 for how it is stored.</li>
        </ul>
      </Section>

      <Section h="3. Your messages are end-to-end encrypted">
        <p>
          Message content — including text, photos and voice notes — is encrypted on your device before it is uploaded.
          The server stores only opaque ciphertext and cannot read the actual content. Even if the server were compromised,
          your private keys never leave your browser, so the messages stay unreadable.
        </p>
        <p className="mt-2">
          To deliver messages reliably we store metadata: sender, recipient, timestamps, delivery/read receipts, and call
          history (who called whom, when, for how long, and whether it was answered). Metadata is not message content.
        </p>
      </Section>

      <Section h="4. Calls and media — peer to peer">
        <p>
          Voice and video calls connect directly between participants where possible (WebRTC). The servers relay only small
          connection signals; the audio/video itself passes device-to-device and is never recorded or stored. Call history
          (time, type, duration, status) is stored so you can see it in your calls list.
        </p>
      </Section>

      <Section h="5. Device permissions">
        <p>
          When you use camera, microphone, notifications, files, storage or contacts features, we ask your browser to grant
          access. Permissions are remembered per device and can be revoked at any time in Settings → Permissions. We only
          access the mic/camera while you are calling or recording, and files only when you choose to share one.
        </p>
      </Section>

      <Section h="6. What stays on your device">
        <p>
          Your encryption identity, session keys, and your in-app permission choices are stored securely in your browser's
          local storage. They are never sent to us. Clearing your browser storage removes them and you can re-register keys
          from Settings → Devices &amp; Security.
        </p>
      </Section>

      <Section h="7. How we use your data">
        <p>
          We use data only to operate the service: deliver messages and calls, show presence (online/last seen), calculate
          read receipts, prevent abuse, and keep the service working. We do not sell your data, we do not show ads, and we do
          not use third-party analytics or tracking scripts.
        </p>
      </Section>

      <Section h="8. Third parties">
        <p>
          If you have no profile picture, a default avatar may be generated by an external image service (DiceBear) — that
          request carries only an anonymous seed derived from your name. Your hosted infrastructure provider stores the data
          on our behalf under our instructions.
        </p>
      </Section>

      <Section h="9. Retention and deletion">
        <p>
          Chat history stays until you clear a chat (the ✕ menu) or delete it. Call history stays until you clear it in your
          calls list. Server backups may retain copies briefly. To delete your account and all associated data, email
          <span className="text-accentDark dark:text-accent"> privacy@example.com</span> — we honour deletion requests within 30 days.
        </p>
      </Section>

      <Section h="10. Security">
        <p>
          We use TLS for all connections, encrypt content end-to-end, restrict abuse with rate limiting, and enforce strict
          security headers. No system is perfect; you can help by keeping your phone number private and logging out on shared
          devices.
        </p>
      </Section>

      <Section h="11. Children">
        <p>
          Waguan is not intended for children under 13 (or the minimum age required by your local law). If you believe a
          child uses the service, contact us and we will remove the account.
        </p>
      </Section>

      <Section h="12. Local storage and cookies">
        <p>
          The app stores a session token, your theme preference, encryption keys, and permission choices in your browser's
          local storage for the app to work — there are no third-party cookies. You can clear it any time from your browser
          settings (this logs you out).
        </p>
      </Section>

      <Section h="13. Changes">
        <p>
          We may update this policy; changes will be posted here with a new date. If we ever process your data in an
          unexpected way we will tell you before doing so.
        </p>
      </Section>
    </PolicyPage>
  );
}